app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_carte:
    resource: "@AppBundle/Resources/config/routing/carte.yml"
    prefix:   /carte

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_role:
    resource: "@AppBundle/Resources/config/routing/role.yml"
    prefix:   /role

app_categorie:
    resource: "@AppBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie
