AppBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleID:
            type: string
            length: 255
            unique: true
        nom:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
